### ISSUE TITLE
Umbrella Projector does not fully protect blocks in Ozone rain

### ISSUE THREAD

**Issue by blu3potato** [SaigoN0Nozomi/nightscape#1]
Basically the title, even with the Umbrella Projector visibly blocking damage and having the Shield Health go down periodically, there's still blocks that's taking damage and eventually destroying itself after a while.

Tested using Mindustry Build 146 and Bleeding Edge 24850, no other mods used.

**Comment by SaigoN0Nozomi** [comment]
Thanks for the feedback, at this moment projector significantly reduce damage, but not to zero.
Despite the fact that I can leave it that way, the rain damage to the block under the umbrella will be even more significantly reduced in next update.
